### ISSUE TITLE
Add link back to github page

### ISSUE THREAD

**Issue by klangner** [timeserieslab/timeserieslab.scalajs#2]

**Comment by GeneralMeow** [comment]
hey there,
i would like to take this on, are you just looking for a regular link going to github.com or a specific page on github ie: timeserieslab/timeserieslab.scalajs?

**Comment by klangner** [comment]
Hi,

I though about link from index.html to: https://github.com/timeserieslab/timeserieslab.scalajs

Somewhere in the footer
